PACKAGE_NAME="linux-firewire"
PACKAGE_VERSION="5.19"

CLEAN="make clean"

MAKE[0]="make all"

BUILT_MODULE_LOCATION[0]="./drivers/firewire"
BUILT_MODULE_LOCATION[1]="./drivers/firewire"

BUILT_MODULE_NAME[0]="firewire-core"
BUILT_MODULE_NAME[1]="firewire-ohci"

DEST_MODULE_LOCATION[0]="/updates/dkms/"
DEST_MODULE_LOCATION[1]="/updates/dkms/"

AUTOINSTALL="yes"
