snd-fireworks-objs := fireworks_command.o fireworks_stream.o fireworks_proc.o \
		      fireworks_control.o fireworks_midi.o fireworks_pcm.o \
		      fireworks_hwdep.o fireworks.o
obj-m += snd-fireworks.o
