snd-firewire-am-unit-objs := am-unit.o
snd-firewire-transceiver-objs := tx-cmp.o tx-fcp.o tx-stream.o tx-midi.o \
				 tx-pcm.o tx.o \
				 rx-stream.o rx-midi.o rx-pcm.o rx.o \
				 trx.o
obj-$(CONFIG_SND_FIREWIRE_AM_UNIT) += snd-firewire-am-unit.o
obj-$(CONFIG_SND_FIREWIRE_TRANSCEIVER) += snd-firewire-transceiver.o
